spring.application.name=service-registrodoctor

server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/db_registrodoctor?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Ruta donde se generará el JSON de la documentación
springdoc.api-docs.path=/api/v1/doctor/v3/api-docs