server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8081"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: "*"
      routes:
        # SERVICIO DE LOGIN (Público)
        - id: service-login
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**

        - id: docs-login # Swagger documentacion login
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/login/v3/api-docs

        # SERVICIO DE DIRECCIONES (Protegido)
        - id: service-direccion
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/direcciones/**, /api/v1/comunas/**, /api/v1/regiones/**
          filters:
            - AuthenticationFilter

        - id: docs-direccion # Swagger documentacion direccion
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/direccion/v3/api-docs
          
        
        # SERVICIO DE PACIENTES (Protegido)
        - id: service-pacientes
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/pacientes/**
          filters:
            - AuthenticationFilter
        
        - id: docs-paciente # Swagger documentacion paciente
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/paciente/v3/api-docs

        # --- SEPARACIÓN DEL SERVICIO DE DOCTORES ---

        # --- SERVICIO DE DOCTORES ---

        # 1. Registro de Doctor (Público)
        - id: doctor-registro-publico
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/doctores
            - Method=POST

        # 2. Gestión de Doctores (Protegido - Requiere ADMIN para ciertas rutas)
        - id: service-doctores-gestion
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/doctores/**
          filters:
            - AuthenticationFilter

        # 3. Gestión de Atenciones (Protegido - Solo DOCTOR)
        - id: service-doctores-atenciones
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/atenciones/**
          filters:
            - AuthenticationFilter

        - id: docs-doctores # Swagger documentacion doctores
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/doctor/v3/api-docs


        # ------------------------------------------

        - id: docs-calendario # Swagger documentacion calendario
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/calendarios/v3/api-docs

        # SERVICIO DE CALENDARIO (Protegido)
        - id: service-calendario
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/calendario/**
          filters:
            - AuthenticationFilter
        
        - id: docs-estadocitas # Swagger documentacion estadocita
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/estadocitas/v3/api-docs

        # SERVICIO DE ESTADO CITA (Protegido)
        - id: service-estadocita
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/estadocita/**
          filters:
            - AuthenticationFilter

        - id: docs-fichamedica # Swagger documentacion fichasmedicas
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/fichasmedicas/v3/api-docs

        # SERVICIO DE FICHA MÉDICA (Protegido)
        - id: service-fichamedica
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/fichas/**
          filters:
            - AuthenticationFilter

        - id: docs-reporte # Swagger documentacion reporte
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/reporte/v3/api-docs

        # SERVICIO DE REPORTES (Protegido - solo acceso interno desde fichamedica)
        - id: service-reportes
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/reportes/**

        - id: docs-telemedicinas # Swagger documentacion telemedicina
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/telemedicinas/v3/api-docs

        - id: service-telemedicina
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/telemedicina/**
          filters:
            - AuthenticationFilter

        - id: service-notificaciones
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/notificaciones/**
          filters:
            - AuthenticationFilter
            
jwt.secret: "39b45678a1b2c3d4e5f678901234567890abcdef1234567890abcdef12345678"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
springdoc:
  swagger-ui:
    urls:
      - name: Servicio direccion
        url: /api/v1/direccion/v3/api-docs
      - name: Servicio login
        url: /api/v1/login/v3/api-docs
      - name: Servicio Doctor
        url: /api/v1/doctor/v3/api-docs
      - name: Servicio paciente
        url: /api/v1/paciente/v3/api-docs
      - name: Servicio calendarios
        url: /api/v1/calendarios/v3/api-docs
      - name: Servicio estadocita
        url:  /api/v1/estadocitas/v3/api-docs
      - name: Servicio fichasmedicas
        url: /api/v1/fichasmedicas/v3/api-docs
      - name: Servicio reportes
        url: /api/v1/reporte/v3/api-docs
      - name: Servicio telemedicina
        url: /api/v1/telemedicinas/v3/api-docs