server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        # Este filtro elimina duplicados y conserva una sola cabecera CORS única
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8081"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: "*"
      routes:
        # SERVICIO DE LOGIN (Público)
        - id: service-login
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**

        - id: docs-login # Swagger documentacion login
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/login/v3/api-docs

        # SERVICIO DE DIRECCIONES (Protegido)
        - id: service-direccion
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/direcciones/**, /api/v1/comunas/**, /api/v1/regiones/**
          filters:
            - AuthenticationFilter

        - id: docs-direccion # Swagger documentacion direccion
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/direccion/v3/api-docs
          

        # SERVICIO DE PACIENTES (Protegido)
        - id: service-pacientes
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/pacientes/**
          filters:
            - AuthenticationFilter

        # --- SEPARACIÓN DEL SERVICIO DE DOCTORES ---

        # --- SERVICIO DE DOCTORES ---

        # 1. Registro de Doctor (Público)
        - id: doctor-registro-publico
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/doctores
            - Method=POST

        # 2. Gestión de Doctores (Protegido - Requiere ADMIN para ciertas rutas)
        - id: service-doctores-gestion
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/doctores/**
          filters:
            - AuthenticationFilter

        # 3. Gestión de Atenciones (Protegido - Solo DOCTOR)
        - id: service-doctores-atenciones
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/atenciones/**
          filters:
            - AuthenticationFilter


        # ------------------------------------------

        # SERVICIO DE CALENDARIO (Protegido)
        - id: service-calendario
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/calendario/**
          filters:
            - AuthenticationFilter

        # SERVICIO DE ESTADO CITA (Protegido)
        - id: service-estadocita
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/estadocita/**
          filters:
            - AuthenticationFilter
        # SERVICIO DE FICHA MÉDICA (Protegido)
        - id: service-fichamedica
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/fichas/**
          filters:
            - AuthenticationFilter

        # SERVICIO DE REPORTES (Protegido - solo acceso interno desde fichamedica)
        - id: service-reportes
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/reportes/**
          filters:
            - AuthenticationFilter

        - id: service-telemedicina
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/telemedicina/**
          filters:
            - AuthenticationFilter

        - id: service-notificaciones
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/notificaciones/**
          filters:
            - AuthenticationFilter
            
jwt.secret: "39b45678a1b2c3d4e5f678901234567890abcdef1234567890abcdef12345678"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
springdoc:
  swagger-ui:
    urls:
      - name: Servicio direccion
        url: /api/v1/direccion/v3/api-docs
      - name: Servicio login
        url: /api/v1/login/v3/api-docs